function valid = valid_prior(u)
    valid = all(u.A(:) > 0) ...
            & all(u.pi > 0) ...
            & all(u.beta > 0) ...
            & all(u.nu > 0) ...
            & all(isfinite(u.mu)) ...
            & all(u.W(:) > 0);